# Application Configuration

# Logger Configuration
logger:
  # Log level: debug, info, warn, error, fatal, panic
  level: info
  # Log format: text, json
  format: json
  # Output to console
  stdout: false
  # Log file configuration
  file:
    # Log file path
    path: "/tmp/logs/app.log"
    # Maximum size of single log file (MB)
    max_size: 100
    # Maximum number of old log files to retain
    max_backups: 5
    # Maximum days to retain old log files
    max_age: 30
    # Compress old log files
    compress: false

# Swagger Configuration
doc_auth:
  ve_merkle: "bedrock"

# DNS Configuration
dns:
  # DNS server address
  endpoint: "http://localhost:8090"

#data base config
db_servers:
  ve_dsn_psql: "host=127.0.0.1 port=5432 user=root password=123456 dbname=ethereum sslmode=disable"
  ve_dsn_mysql: ""

#contracts config
contracts:
  airdrop:
    rpc: "https://eth-sepolia.public.blastapi.io"
    address: "0xcFB4AefB7B655d26420Ab9f208172F5e289F2D35"